ARDUINO_DIR            = /usr/share/arduino
TARGET                 = test_moteur_et_servo
ARDUINO_LIBS           = Servo
MCU                    = atmega328p
F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE   = 115200
AVRDUDE_ARD_PROGRAMMER = arduino

#include /usr/share/arduino/Arduino.mk
include Arduino.mk

